version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs: 
  build-medium: 
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps: 
      - checkout
      - run: uname -a
      - run: cat /proc/cpuinfo 
      - run: make
  build-runner: 
    machine: true
    resource_class: kurumai/arm-runner
    steps: 
      - checkout
      - aws-cli/install
      - run: uname -a
      - run: cat /proc/cpuinfo 
      - run: make
workflows: 
  build:
    jobs: 
      # - build-medium
      - build-runner
